### ISSUE TITLE
Missing content

### ISSUE THREAD

**Issue by piglickjf** [pathminder/pathminder.github.io#3]
I notice that most of the content that used to be on here is missing. Is it gone for good, or is just an error/under construction type thing?

**Comment by drumanagh** [comment]
It looks like an update to the Jekyll version used by Github Pages broke a bunch of stuff. I'll see about fixing it.

**Comment by drumanagh** [comment]
I think I've fixed up most of the obviously broken stuff. Let me know if you spot anything else missing?
