### ISSUE TITLE
Unorthodox Method and Soul Hunter

### ISSUE THREAD

**Issue by Hykatai** [pathminder/pathminder.github.io#4]
I noticed that you have Unorthodox Method as a Social Trait. On Pathfinder, it's listed as (Regional, any). Is this a revision? 

Also, does the Soul Hunter lose the deadly strike ability of the Stalker? Again, on Pathfinder, deadly strike is replaced by Soulburning.

Thanks for taking the time to answer this newbie.

**Comment by drumanagh** [comment]
> I noticed that you have Unorthodox Method as a Social Trait. On Pathfinder, it's listed as (Regional, any). Is this a revision?

That was an error. It's now fixed.

> Also, does the Soul Hunter lose the deadly strike ability of the Stalker? Again, on Pathfinder, deadly strike is replaced by Soulburning.

The missing Soulburning entry was an error and is now fixed.
